### ISSUE TITLE
No Longer Works on DS Remastered

### ISSUE THREAD

**Issue by Zunawe** [Quidrex/DSDeaths#1]
Doesn't seem to detect deaths or write any files on Dark Souls: Remastered. Tested today. Probably just a patch that changed the address.

**Comment by Quidrex** [comment]
I just rechecked the memory address, it still works fine for me. Even if the address was wrong, the file would be written to the working directory where the program is run from. Does the console log indicate that a process was found?

**Comment by Zunawe** [comment]
Oh, it is working. I guess I set it up wrong somehow. Sorry about that. Guess I'll take the comment to thank you for your work and close the issue.
