### ISSUE TITLE
Elden Ring 1.02.3 without EAC not working

### ISSUE THREAD

**Issue by Andreas-737** [Quidrex/DSDeaths#12]
Program doesnt find Elden Ring game (Patch 1.02.3) even if i disable EAC. Donno if it is because of wrong usage or the patch.

**Comment by Danzoui** [comment]
Fixed - https://github.com/Quidrex/DSDeaths/pull/13
You can use this for now:
[DSDeaths.zip](https://github.com/Quidrex/DSDeaths/files/8237214/DSDeaths.zip)

**Comment by Andreas-737** [comment]
This solved it, thx.
