### ISSUE TITLE
Doesn't work on Elden Ring patch 1.02.3

### ISSUE THREAD

**Issue by LOCKhart07** [Quidrex/DSDeaths#14]
Elden ring process is found but the text file always shows zero deaths. EAC is disabled. 
![image](https://user-images.githubusercontent.com/33950242/158123788-531b8099-664f-46f4-a3ee-9c4df5760803.png)
![image](https://user-images.githubusercontent.com/33950242/158123803-d63d0431-3965-45bc-8373-ad07ef7c3539.png)

**Comment by Danzoui** [comment]
Fixed - https://github.com/Quidrex/DSDeaths/issues/12
Please don't close this thread so others can see it.

**Comment by Quidrex** [comment]
1.02.3 is out of date now
