### ISSUE TITLE
Elden Ring, New address, Patch 1.03, 1.03.1

### ISSUE THREAD

**Issue by Danzoui** [Quidrex/DSDeaths#16]
Fixed - https://github.com/Quidrex/DSDeaths/pull/15
You can use this for now:

[DSDeaths.zip](https://github.com/Quidrex/DSDeaths/files/8287462/DSDeaths.zip)

Mirror (github is now very badly working) - https://pixeldrain.com/u/Lk8DatSA

**Comment by Quidrex** [comment]
I was on holidays, will merge and release tomorrow

**Comment by Quidrex** [comment]
Fixed in v0.4.1
