### ISSUE TITLE
Doesn't work for Dark Souls 3

### ISSUE THREAD

**Issue by Assios** [Quidrex/DSDeaths#21]
After the Dark Souls 3 update, I'm no longer getting the correct number. It's constantly displaying the number 539251853, so I'm assuming it's reading from the wrong memory address.

**Comment by Quidrex** [comment]
Unfortunately the new patch seems to have some kind of debugger detection; as soon as I set a breakpoint the game crashes. I'm not yet sure how to work around that to find the new pointer.

**Comment by Danzoui** [comment]
https://github.com/Quidrex/DSDeaths/pull/22

**Comment by Quidrex** [comment]
Merged in v0.4.4
