### ISSUE TITLE
Doesn't work with Elden Ring 1.06.

### ISSUE THREAD

**Issue by Foolkep** [Quidrex/DSDeaths#23]

**Comment by Foolkep** [comment]
Also doesnt work with 1.07.

**Comment by Danzoui** [comment]
Fixed - https://github.com/Quidrex/DSDeaths/pull/31

You can use this for now:
[DSDeaths.zip](https://github.com/Quidrex/DSDeaths/files/10789429/DSDeaths.zip)

Please don't close this thread so others can see it.

**Comment by Quidrex** [comment]
Fixed for 1.09.1 in v0.5.1
