### ISSUE TITLE
Doesn't work for Dark Souls Remastered

### ISSUE THREAD

**Issue by nyomen** [Quidrex/DSDeaths#24]
They repaired the Onlinefeature in Dark Souls Remastered and probably changed the memory address. So the counter is not working at all atm.

**Comment by nyomen** [comment]
Ok. I just digged into the rabbit hole on my own.

I used artmoney software to grab my deaths from dsr, and the memory location is changing every time you load a save game.... So it's nearly impossible to find out the spot of the actual deaths as long as you don't save death count from the last time, and then it's still just a maybe.

The only possibility to get your death count back is by rolling back the steam version, start the game and run the tool. Since the old version is writing the death count exactly at the same memory location in the ram.

So.... There is much more effort needed to bring this tool to functionality again and even if, if you would die without the tool active it would be just lost in anyway.

So thx for the work on that tool, but I don't think I will use it again since fromsoftware broke the basic idea of the game with the dynamic memory thing.

**Comment by Danzoui** [comment]
Have you used pointers? The address in memory changes in most games when you restart. I'll take a look later, okay.

**Comment by nyomen** [comment]
Nope I just figured out particular addresses and watched them.

**Comment by Danzoui** [comment]
Watch this video - https://youtu.be/8oC0w6WhZ1E. It shows quite clearly how to find the desired address using the Cheat Engine.

**Comment by nyomen** [comment]
I know how this works.... I know how to find a memory adress and it is the same always on the older version but on the newer it switches.

I'm not stupid. There is a significant difference between the older and the newer version, the newer version switches adresslocations every time, I told this alrdy in the text above. 
So first. Recreate my issue and get it, before answer with generic YouTube videos.
It's not about the specific adress location, it's about the switching of the locations.

**Comment by Danzoui** [comment]
Fixed - https://github.com/Quidrex/DSDeaths/pull/25
You can use this for now:
[DSDeaths.zip](https://github.com/Quidrex/DSDeaths/files/10145989/DSDeaths.zip)
Please don't close this thread for others to see.

**Comment by nyomen** [comment]
For real? Users got an issue with your software, you say there is no problem and denie the issue.
Nice. I will count on my own.

**Comment by Danzoui** [comment]
The address has changed. I found a new one. I gave you the corrected application. I'm not the author of the repository and can't release it.

**Comment by nyomen** [comment]
Ok will try it. Thx.

**Comment by nyomen** [comment]
Ok its back working. Thank you very much. Wondering if artmoney could do the same as cheatengine.

**Comment by Danzoui** [comment]
Seems yes. There is an option to search for pointers. But Cheat Engine seems to be a much more powerful tool than ArtMoney.

**Comment by Quidrex** [comment]
Thanks again @Danzoui for the merge request, update released.

**Comment by Danzoui** [comment]
@Quidrex You do not want to update the address for the Elden Ring? I just don't have the game installed right now.

**Comment by Quidrex** [comment]
I just did not get around to it, I feared it might behave like Dark Souls III and crash if the Cheat Engine debugger is attached.

**Comment by Danzoui** [comment]
Try DBVM. Thanks to him, Dark Souls Remastered did not crash when I attached the debugger.
<details>
<summary>screen</summary>

![1](https://user-images.githubusercontent.com/61109303/205603605-8a0d1815-76d4-408a-9faf-3b50d9ec8339.png)
</details>
And as far as I know, Elden Ring does not crash immediately when a default debugger is attached, which makes it possible to obtain the necessary data.
