### ISSUE TITLE
Counter with DS2 not working anymore

### ISSUE THREAD

**Issue by Andreas-737** [Quidrex/DSDeaths#26]
Deathcounter isn’t working anymore with DS2 Scholar of the first sin. DSDeaths.txt stays at zero deaths.

Thx for help on this :)

**Comment by Danzoui** [comment]
New address - "DarkSoulsII.exe"+016732B0 28 4C0
Need to check if this works in the standard game.
You can use this for now:
[DSDeaths.zip](https://github.com/Quidrex/DSDeaths/files/10221838/DSDeaths.zip)

Please don't close this issue for others to see.

**Comment by Andreas-737** [comment]
> 

Thx. Unfortunately, the provided exe writes a one into the text file, but i died about 110 times.

**Comment by Danzoui** [comment]
@Andreas-737 Have you restarted the program? I don't know why, but when exiting in the menu, the counter is not updated, although everything is fine in the Cheat Engine.

**Comment by Andreas-737** [comment]
> Danzoui

I restarted ds2 and the deathcounter. i also updated the sourcecode and compiled it. same result...

**Comment by Danzoui** [comment]
Strange... It's just that everything works fine for me. Can you check this address in Cheat Engine?

**Comment by Danzoui** [comment]
"DarkSoulsII.exe"+0168B948 3A0 1F4
Try this:
[DSDeaths.zip](https://github.com/Quidrex/DSDeaths/files/10231582/DSDeaths.zip)

**Comment by Danzoui** [comment]
It turns out that the game has several death counters. The first counter shows death along with new game plus. And the second counter - the deaths of only the current walkthrough.

Address of the second counter:
"DarkSoulsII.exe"+0168B948 3A0 294

**Comment by Danzoui** [comment]
It turns out that the game has several death counters. The first counter shows deaths along with new game plus. And the second counter - the deaths of only the current walkthrough.

Address of the second counter:
"DarkSoulsII.exe"+0168B948 3A0 294

**Comment by Andreas-737** [comment]
> It turns out that the game has several death counters. The first counter shows deaths along with new game plus. And the second counter - the deaths of only the current walkthrough.
> 
> Address of the second counter: "DarkSoulsII.exe"+0168B948 3A0 294

Hey,

Unfortunately, none of the above worked for me...
I use 1.03, yes. 
Unfortunately, i never used the cheat engine. Nevertheless, i downloaded it, used the cheat table and found the "Total Deaths" entry in the cheat table.
It says:
Address: P->7FF42002F1C4
Type: 4 Bytes
Value: 133

Value: 133 is my death count.

But i guess, it isnt the memory location i have to add in the c# code. Maybe i have to hit "Memory View" or context menue "browse this memory region"?! But how to progress then? Maybe u can give me a little hint, so i can investigate further on it and let u know the result :)

**Comment by Danzoui** [comment]
@Andreas-737  You need to look for a pointer. Watch this video https://youtu.be/8oC0w6WhZ1E , it will show you how to find them correctly. And yes, unfortunately I again found that I had found the wrong pointer. With other games from FromSoftware, it was usually much easier. There are a lot of pointers here and I can't find the right one...

**Comment by Danzoui** [comment]
Most likely you will need to restart the game several times to weed out wrong pointers.

**Comment by Danzoui** [comment]
@Andreas-737  [CE.zip](https://github.com/Quidrex/DSDeaths/files/10232618/CE.zip)

1 scan 1.PTR - pointer scan for 1 address
2 scan 1.PTR - pointer scan for 2 address
DarkSoulsII.CT - Table

**Comment by Danzoui** [comment]
@Andreas-737  Check this:
[CE.zip](https://github.com/Quidrex/DSDeaths/files/10233024/CE.zip)

1 scan 1 rescan.PTR - pointer scan for 1 address
2 scan 1 rescan.PTR - pointer scan for 2 address
DarkSoulsII.CT - Table

**Comment by Danzoui** [comment]
"DarkSoulsII.exe"+016148F0 D0 490 104
![image](https://user-images.githubusercontent.com/61109303/207816165-2e5ff4e1-3dfc-44e7-a254-15562470c8ff.png)

If that doesn't work... Need to completely rewrite the code so don't have to worry about looking up pointers every time. And make it work on all patches.

**Comment by Andreas-737** [comment]
> "DarkSoulsII.exe"+016148F0 D0 490 104 ![image](https://user-images.githubusercontent.com/61109303/207816165-2e5ff4e1-3dfc-44e7-a254-15562470c8ff.png)
> 
> If that doesn't work... Need to completely rewrite the code so don't have to worry about looking up pointers every time. And make it work on all patches.

Hey, i wasnt able to sort it all out by my own. I was able to to identify the offsets, but i have no glue how i figure out the base as the clip u sent didnt provide me the information i searched for. Nevertheless, mixed up your solution and mine and end up with this:

0x016148F0, 0xD0, 0x490, 0x1A4

This worked for me for the moment.
So thank u very much for your help!

**Comment by Danzoui** [comment]
@Andreas-737 This offset is only for the current game, this address will incorrectly show deaths for the new game plus. Use **0x104** instead

**Comment by Quidrex** [comment]
I'd love to find a solution that does not need to be updated with every patch but I think without debug symbols we are out of luck. I'm not sure any kind of heuristic would work here, maybe reading from the save file instead of from memory would be worthwhile. The death counter for DS1 includes NG+ but I am indifferent whether to include it or not. Maybe the program could write two files in a future version.

**Comment by Andreas-737** [comment]
> @Andreas-737 **0x1A4** This offset is only for the current game, this address will incorrectly show deaths for the new game plus. Use **0x104** instead

Thx for the advice. Currently i only need the current game, but 104 also produces the correct death count, so i used this one :)

**Comment by Danzoui** [comment]
@Quidrex @Andreas-737  Do you have the standard version? I don't have a standard game. I only need the exe file.

**Comment by Andreas-737** [comment]
> @Quidrex @Andreas-737  Do you have the standard version? I don't have a standard game. I only need the exe file.

I have Scholar of the first sin version 1.03.

**Comment by Danzoui** [comment]
@Quidrex
In general, here is the address for SOTFS (NG+ and current game):
**`0x16148F0, 0xD0, 0x490, 0x104`**

<details>
Only current game:

**`0x16148F0, 0xD0, 0x490, 0x1A4`**
</details>

Regular game version (NG+ and current game):
**`0x1150414, 0x74, 0xB8, 0x34, 0x4, 0x28C, 0x100`**

<details>
Only current game:

**`0x1150414, 0x74, 0xB8, 0x34, 0x4, 0x28C, 0x1A0`**
</details>

<details>
There is also a third address, I don't know what it is for, but it duplicates the value of the first address:

**`0x1150414, 0x54, 0x14, 0x1C, 0x14, 0x14, 0x21C`**
</details>

I think that it is possible to compare SOTFS and the regular version of the game by the description of the exe file.

**Comment by Quidrex** [comment]
I did develop support for the regular version at one point but for some reason never merged it. l used `IsWow64Process` to differentiate the versions. I'll readd it.

**Comment by Quidrex** [comment]
Implemented support in v0.5.0
