### ISSUE TITLE
Works only randomly for DS3

### ISSUE THREAD

**Issue by blackoutroulette** [Quidrex/DSDeaths#28]
Worked a few days ago, currently the counter stays at zero. The game gets detected in the console. Restarting the tracker does nothing.

**Comment by Danzoui** [comment]
@blackoutroulette Hmm, strange. There were no new patches? Is the patch still 1.15.1? Maybe you switched to a new game plus or something? Try starting a new game and test in it.

**Comment by blackoutroulette** [comment]
Well looks like my buddy who had the problem selected the wrong texfile in OBS. Sorry for opening the the issue too soon, I really had faith in him because he has a computer science background. 😅
