### ISSUE TITLE
"Encountered null pointer." Spam

### ISSUE THREAD

**Issue by DanzoGit** [Quidrex/DSDeaths#30]
The moment the game starts, the console starts spamming "Encountered null pointer.".
Tested with Dark Souls 3. I don't know about other games. This moment needs to be changed.

<details>
<summary>screen</summary>

![1](https://user-images.githubusercontent.com/61109303/219945130-3e2c7fa8-9340-4e4f-961d-e6bda8d3af8d.png)
</details>

P.S. Death counts correctly on the latest patch.

**Comment by CodeByAidan** [comment]
@Quidrex, getting same problem on Dark Souls: Remastered
