### ISSUE TITLE
DS3 update broke counter

### ISSUE THREAD

**Issue by lethargicwaldo** [Quidrex/DSDeaths#33]
It looks like the update that was rolled out on January 12th broke DS3(v1.15.2 / Reg v1.35). I'm assuming it's a busted pointer.

**Comment by Danzoui** [comment]
@lethargicwaldo Have you tried launching the game first and then the DSDeaths?

**Comment by lethargicwaldo** [comment]
Yeah I've tried it both ways.

**Comment by Danzoui** [comment]
@lethargicwaldo Strange. Everything works correctly for me. Do you have a new game or a new game plus?

**Comment by lethargicwaldo** [comment]
I checked both NG and NG+, the DSDeaths.txt file is filling up with "539251853" I loaded up some existing files that I know the death count for as well and all keep showing this same number. I re-downloaded the current version of the DSDeaths tracker to be sure I wasn't using anything out of date as well.

**Comment by Danzoui** [comment]
@lethargicwaldo I checked on steam and non-steam version of the game. Everywhere the counter works correctly. Do you have a clean steam version without mods?

**Comment by Danzoui** [comment]
@lethargicwaldo Brother, I don't know what's the problem. My friend also checked the counter, everything works for him too. You can try to find the pointer yourself using the Cheat Engine. Here is the guide - https://youtu.be/8oC0w6WhZ1E

@Quidrex , maybe you know why such a problem can be?

**Comment by Disorbs** [comment]
question I'm using a cracked DS3 1.15.0 and i use the version for that but every time i close the game and close the counter it goes back to 0 all the time is that normal? i think it doesn't count sometimes too not sure.

**Comment by Danzoui** [comment]
@Disorbs Yes, if you do not have a save loaded, it will show 0, this is normal.
