### ISSUE TITLE
I get "0" but I've definitely died several times.

### ISSUE THREAD

**Issue by donmularz** [Quidrex/DSDeaths#5]
It seems to run fine, the window comes up and says it detected Dark Souls: Remastered.  I close the file and check the .txt and it says "0".  Does it still count if I retrieve my souls and stuff?

Edit:  I re-read the description, does this only count the deaths that happen while it's running?  That's cool too, but you might want to make it a bit more clear for idiots like me lol

**Comment by Quidrex** [comment]
As soon as you close the save file the memory location it reads goes to 0. You have to read the file while the save file is open, it then shows the accumulated number of deaths in that file.
