### ISSUE TITLE
Not working for DS2?

### ISSUE THREAD

**Issue by Tapport-tv** [Quidrex/DSDeaths#9]
Hi all, sorry for opening this but I'm not sure if it's an issue or not.

I have Dark Souls II (not the scholar version) and my death counter isn't working. The exe detects Dark Souls II when I launch it but then the text file never updates when I continue playing. I'm not sure if this doesn't work for base DS2 or if there is a problem so I was just hoping to confirm.

I see that it's not listed but I'm not sure of the differences for each version.

In case it doesn't work are there any plans to update it? Thanks so much for the software by the way, it was great for my DS1 playthrough!

**Comment by Quidrex** [comment]
Hi, that is correct, DS2 original does not work. Mainly because I don't own it and didn't think anyone would still play it 😅 
I'll se what I can do.

**Comment by Tapport-tv** [comment]
> Hi, that is correct, DS2 original does not work. Mainly because I don't own it and didn't think anyone would still play it 😅 I'll se what I can do.

lol, yeah... First time playing through these games so I didn't know there were multiple versions. In case I you can give a quick explanation on how to get you the info needed to add support I'd love to help out. I understand you're using cheat engine?

**Comment by Quidrex** [comment]
Please try this experimental version: https://github.com/Quidrex/DSDeaths/releases/download/untagged-8ff53d81b0d6fe875250/DSDeaths.exe

**Comment by Tapport-tv** [comment]
First off, thanks so much for the quick turn around! I know this probably won't benefit many more given that DSII is so old now but your effort is totally appreciated.

I tested both versions tonight and I'm not sure if it's just me but they don't seem to update death count (reading 0 with v1 and v2). Dark Souls II is still detected but the .txt isn't being updated. I tried dying to see if it might get the death count updated but no luck. In case there is anything else you recommend I try, just let me know!

**Comment by Quidrex** [comment]
I found an error, please try:

https://drive.google.com/file/d/1pVtNlfPAQxs4Nwj_heetY1WP5wKFBl0_/view?usp=sharing
https://drive.google.com/file/d/12CfqSYm6UHrh8YeuZK7c6-_xpPN9gyxi/view?usp=sharing

As the servers are down at the moment I cannot check online, but my guess would be that the first one might be the worldwide death count and the second one the local one.

**Comment by Tapport-tv** [comment]
v3 and v4 still aren't working on this end. Is there anything I might be doing wrong?

I launched DSDeaths before starting DSII and also tried to delete my txt to make sure new ones are being generated but it keeps spitting out 0. I don't know if it helps at all but when going from DS3 with 145 deaths to DS2, it also isn't updating to 0 or the actual death count on the save of 39, just stays at 145 while playing DS2.

**Comment by Quidrex** [comment]
That is weird, I just tried it with the current Steam release and v3 does work for me. v4 also works but only counts the deaths in the current NG+. I will clean up the code and prepare a release.

**Comment by Tapport-tv** [comment]
I'll have to give it another go tonight. I can't think of anything I'd have done wrong but we'll just have to see.

**Comment by Quidrex** [comment]
After all the Elden Ring shenanigans I had another look and found a bug where it does not write a file if the death count is 0. I also added a few debug outputs as I'm not sure where else to look, it works for me. You can try this version, it is based on the current Elden Ring compatible version.
[DSDeaths.zip](https://github.com/Quidrex/DSDeaths/files/8188259/DSDeaths.zip)

**Comment by Tapport-tv** [comment]
Okay, thanks for the update. I'll test this weekend and report back soon. You're the best!

**Comment by Tapport-tv** [comment]
Confirmed working on DS2 now, thanks so much!
